/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : main.c
  * @brief          : Main program body
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2025 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */
/* USER CODE END Header */
/* Includes ------------------------------------------------------------------*/
#include "main.h"

/* Private includes ----------------------------------------------------------*/
/* USER CODE BEGIN Includes */

/* USER CODE END Includes */

/* Private typedef -----------------------------------------------------------*/
/* USER CODE BEGIN PTD */

/* USER CODE END PTD */

/* Private define ------------------------------------------------------------*/
/* USER CODE BEGIN PD */

/* USER CODE END PD */

/* Private macro -------------------------------------------------------------*/
/* USER CODE BEGIN PM */

/* USER CODE END PM */

/* Private variables ---------------------------------------------------------*/
UART_HandleTypeDef huart2;

/* USER CODE BEGIN PV */

/* USER CODE END PV */

/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_USART2_UART_Init(void);
/* USER CODE BEGIN PFP */

/* USER CODE END PFP */

/* Private user code ---------------------------------------------------------*/
/* USER CODE BEGIN 0 */

/* USER CODE END 0 */

/**
  * @brief  The application entry point.
  * @retval int
  */
#include <math.h>
#define ADC_FS 3.3

volatile uint16_t voltage = 0;
volatile float voltage_f = 0;
uint16_t dutyc = 0;
void ADC_IRQHandler() {
	if(((ADC1->SR >> ADC_SR_EOC_Pos) & 0x01)) {
		voltage = (uint16_t)ADC1->DR;
		voltage_f = voltage*(ADC_FS/pow(2, 12));
		dutyc = 500 + (voltage * 2000) / 4095;
		ADC1->CR2 |= (0x1 << ADC_CR2_SWSTART_Pos);
	}
}

void ADC_Init() {
	/* GPIO Configuration */
	// Provide clock to PORTA (PA_0 and PA_1 are associated to CH0 and CH1)
	RCC->AHB1ENR |= (1 << RCC_AHB1ENR_GPIOAEN_Pos); 	// Clock to GPIOA

	// Set both GPIOs in Analog mode
	GPIOA->MODER |= (3 << GPIO_MODER_MODE0_Pos);		// Set PA0 in Analog mode

	/* ADC Configuration */
	// Provide clock to ADC1
	RCC->APB2ENR |= (1 << RCC_APB2ENR_ADC1EN_Pos); 	// Clock to ADC1


	ADC1->CR2 	|= (0x01 << ADC_CR2_ADON_Pos);			// (ADON) Power On ADC1
	ADC1->CR2 	&= ~(0x01 << ADC_CR2_CONT_Pos);			// (CONT) Single Conversion Mode
	ADC1->SQR3 	&= ~(0x1F << 0);						// Clear before Selection of Channel 0
	ADC1->SQR3 	|= (0x00 << 0);							// Selection of Channel 0
	ADC1->CR1 	&= ~(0x1 << ADC_CR1_SCAN_Pos); 			// (SCAN) Disable Scan Mode
	ADC1->CR1 	&= ~(0x1 << ADC_CR1_DISCEN_Pos); 		// (DISCEN) Disable Discontinuous Mode
	ADC1->CR1 	&= ~(0x07 << ADC_CR1_DISCNUM_Pos);		// (DISCNUM) Clear Number of Discontinuous Channels
	ADC1->CR2 	&= ~(0x1 << ADC_CR2_ALIGN_Pos); 	// (ALIGN) Align right
	ADC1->SMPR2 	&= ~(0x0F << ADC_SMPR2_SMP0_Pos);		// Set 3 Cycles per Samples
	ADC1->CR1 	&= ~(0x03 << ADC_CR1_RES_Pos);			// 12 Bit resolution
	ADC1->CR2 	|= (0x01 << ADC_CR2_EOCS_Pos); 			// (EOCS) Notify when each conversion of a sequence is complete
	ADC1 ->CR1 	|= (0x01 << ADC_CR1_EOCIE_Pos); 		// (EOCIE) Generate an interrupt every time EOC is set

	NVIC_EnableIRQ(ADC_IRQn); 		// Check file stm32f446xx.h for the name definition
	NVIC_SetPriority(ADC_IRQn, 0); 	// Priority
	ADC1->CR2 |= (0x1 << ADC_CR2_SWSTART_Pos);
}
void TIM3_PWM_setup() {
	/* GPIO SetUp (PA6 -> TIM3_CH1) */
	RCC->AHB1ENR |= (1 << RCC_AHB1ENR_GPIOAEN_Pos);		// Enable GPIO6
	GPIOA->MODER |= (2 << 12); 							// Alternate function mode
	GPIOA->AFR[0] = (2 << 24); 							// Alternate function n2 for PA6 (TIM3 CH1)
	GPIOA->OSPEEDR 	|= (3 << 12);  						// High Speed for PIN PA6

	/* TIM3 SetUp */
	RCC->APB1ENR |= (1 << RCC_APB1ENR_TIM3EN_Pos); 		// Clock to TIM3

	/* CR1 Configuration */
	TIM3->CR1 &= ~(1 << TIM_CR1_UDIS_Pos); 		// Update event enabled
	TIM3->CR1 &= ~(1 << TIM_CR1_URS_Pos);		// Update event generated by any source
	TIM3->CR1 &= (1 << TIM_CR1_DIR_Pos); 		// Upcounting direction
	TIM3->CR1 &= (0x03 << TIM_CR1_CMS_Pos); 	// (00) Edge aligned mode
	TIM3->CR1 |= (1 << TIM_CR1_ARPE_Pos); 		// Auto reload preload enabled

	TIM3->CCMR1 &= ~(0x03 << TIM_CCMR1_CC1S_Pos); 	// TIM3_CH1 configured as output
	TIM3->CCMR1 |= (1 << TIM_CCMR1_OC1PE_Pos); 		// Preload CCR1 register as well
	TIM3->CCMR1 |= (0x6 << TIM_CCMR1_OC1M_Pos); 	// PWM Mode 1

	TIM3->CCER |= (1 << TIM_CCER_CC1E_Pos); 				// Enable output channel 1
	TIM3->CCER |= (0 << TIM_CCER_CC1P_Pos); 				// Active low

	TIM3->PSC = 84 - 1; 						// CNT incremented every us
	TIM3->ARR = 20000 - 1; 						// Update event every seconds
	TIM3->CCR1 = 1000 - 1;

	TIM3->EGR |= (1 << TIM_EGR_UG_Pos); 		// Fire an update event to update shadow registers
}

volatile uint8_t time_elapsed = 0;
uint16_t counter = 0;
void TIM6_DAC_IRQHandler() {
	if((TIM6->SR >> TIM_SR_UIF_Pos) & 0x01) { //se ha raggiunto il valore di ARR
		NVIC_ClearPendingIRQ(TIM6_DAC_IRQn);
		time_elapsed = 1;                    //ha completato il conteggio
		TIM6->CR1 &= ~(1 << TIM_CR1_CEN_Pos); //disabilita il conteggio
		TIM6->SR &= ~(1 << TIM_SR_UIF_Pos); //  //resetta il flag dell'interrupt
	}
}

uint8_t measure_collected = 0;
uint32_t measure = 0;
void EXTI1_IRQHandler() {
	NVIC_ClearPendingIRQ(EXTI1_IRQn);
	/*se l'interrupt avviene perchè echo è 1 azzera il contatore e pone un limite alto
	 *per evitare overflow abilitando il conteggio e cominciando a contare.*/
	if((GPIOC->IDR >> 1) & 0x01) {
		TIM6->ARR = 65000;
		TIM6->CNT = 0;
		TIM6->CR1 |= (1 << TIM_CR1_CEN_Pos);
		measure_collected = 0;
		/*Se l'interrupt scatta per un fronte di discesa allora il conteggio viene disabilitato, e il
		 * valore a cui siamo arrivati è in measure (tempo di andata e ritorno dell'onda) */
	} else {
		TIM6->CR1 &= ~(1 << TIM_CR1_CEN_Pos);
		measure = TIM6->CNT;
		measure_collected = 1;
	}
	EXTI->PR |= (0x01 << EXTI_PR_PR1_Pos); //va pulito altrimenti risulta ancora la
	                                       //richiesta di interrupt e l'ISR viene richiamata
}


void TIM6_basic_setup() {

	RCC->APB1ENR |= (1 << RCC_APB1ENR_TIM6EN_Pos); 		// Clock to TIM6

	TIM6->CR1 &= ~(1 << TIM_CR1_UDIS_Pos); // Update event enable ( viene chiamato l'handler se c'è overflow e altri
	TIM6->CR1 |= (1 << TIM_CR1_URS_Pos);   // Update event generated only by overflow/underflow
	TIM6->PSC = 84 - 1; 				   // CNT incremented every nanoseconds

	TIM6->DIER |= (1 << TIM_DIER_UIE_Pos); 		// Trigger an interrupt every update event
	NVIC_EnableIRQ(TIM6_DAC_IRQn);				// Enable interrupt for TIM6
	NVIC_SetPriority(TIM6_DAC_IRQn, 0); 		// Set Priority
}

void delay_micro_s(uint16_t delay) {
	TIM6->ARR = delay - 1; //auto-reload value (il timer si resetta a questo valore)
	TIM6->CNT = 0; //valore di conteggio iniziale
	TIM6->CR1 |= (1 << TIM_CR1_CEN_Pos); //abilita il conteggio
	while(!time_elapsed) {}; //finchè time elapsed è 1 ()
	time_elapsed = 0;
}


void hc_sr04_init() {
	RCC->AHB1ENR |= (1 << RCC_AHB1ENR_GPIOCEN_Pos); //abilita il clock alla porta C

	/** Trigger pin configuration **/
	GPIOC->MODER |= (0x01 << 0);  // Set Output PC0 come Trigger (sta alto almeno 10 microsecondi
	                              // appena si abbassa il sensore invia le onde)
	// Push-Pull output
	GPIOC->OTYPER &= ~(0x1 << 0);

	/**Echo pin configuration **/
	GPIOC->MODER  &= ~(0x03 << 2); // Set Input PC1 Echo ci serve leggere per quanto tempo rimane alto

	/* SYStem ConFiGuration (Multiplexer) */
	SYSCFG->EXTICR[0] |= (SYSCFG_EXTICR1_EXTI1_PC); //abilita l'EXTI su PC1 (0010: PC[1]) come sorgente esterna

	/* EXTernal Interrupt configuration */
	EXTI->IMR  |= (EXTI_IMR_IM1); //toglie la maschera all'interrupt
	EXTI->FTSR |= (0x01 << EXTI_FTSR_TR1_Pos);// abilito l'interrupt sul fronte di salita
	EXTI->RTSR |= (0x01 << EXTI_RTSR_TR1_Pos);// abilito l'interrupt sul fronte di discesa

	/* NVIC Configuration */
	NVIC_EnableIRQ(EXTI1_IRQn);
	NVIC_SetPriority(EXTI1_IRQn, 0);

	TIM6_basic_setup();
}

void set_triger() {
	GPIOC->ODR |= (1 << 0); //alza il segnale di trigger
}

void clear_triger() {
	GPIOC->ODR &= ~(1 << 0);//abbassa il segnale di trigger
}

float meas_dist() {
	clear_triger(); 	// keep trigger low
	delay_micro_s(3);	// for at least 3 mu_s

	set_triger();		// set trigger high
	delay_micro_s(10);	// for at least 10 mu_s
	clear_triger();		// clear trigger to start ultrasonic burst transmission

	while(!measure_collected);	// wait for measurement to be collected (look EXTI ISR) finche non
	                            // legge per quanto tempo echo è stato alto
	return 0.5*0.000343*measure;// return measurement (twice speed of sound times echo rise time (measure))
}
float measure_f;

int main(void)
{

  /* USER CODE BEGIN 1 */

  /* USER CODE END 1 */

  /* MCU Configuration--------------------------------------------------------*/

  /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
  HAL_Init();

  /* USER CODE BEGIN Init */

  /* USER CODE END Init */

  /* Configure the system clock */
  SystemClock_Config();

  /* USER CODE BEGIN SysInit */

  /* USER CODE END SysInit */

  /* Initialize all configured peripherals */
  MX_GPIO_Init();
  MX_USART2_UART_Init();
  //setup servo motor
  TIM3_PWM_setup();
  ADC_Init();
  //setup ultrasound sensor
  hc_sr04_init();

  TIM3->CR1 |= (1 << TIM_CR1_CEN_Pos);

  while (1)
  {
    /* USER CODE END WHILE */
	  measure_f = meas_dist();
	  if (measure_f <=0.04){
		  TIM3->CCR1=1500-1;
	  } else{
		  TIM3->CCR1=2500-1;
	  }
      HAL_Delay(100);

    /* USER CODE BEGIN 3 */
  }
  /* USER CODE END 3 */
}

/**
  * @brief System Clock Configuration
  * @retval None
  */
void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  /** Configure the main internal regulator output voltage
  */
  __HAL_RCC_PWR_CLK_ENABLE();
  __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE3);

  /** Initializes the RCC Oscillators according to the specified parameters
  * in the RCC_OscInitTypeDef structure.
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
  RCC_OscInitStruct.HSIState = RCC_HSI_ON;
  RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSI;
  RCC_OscInitStruct.PLL.PLLM = 16;
  RCC_OscInitStruct.PLL.PLLN = 336;
  RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV4;
  RCC_OscInitStruct.PLL.PLLQ = 2;
  RCC_OscInitStruct.PLL.PLLR = 2;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }

  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_2) != HAL_OK)
  {
    Error_Handler();
  }
}

/**
  * @brief USART2 Initialization Function
  * @param None
  * @retval None
  */
static void MX_USART2_UART_Init(void)
{

  /* USER CODE BEGIN USART2_Init 0 */

  /* USER CODE END USART2_Init 0 */

  /* USER CODE BEGIN USART2_Init 1 */

  /* USER CODE END USART2_Init 1 */
  huart2.Instance = USART2;
  huart2.Init.BaudRate = 115200;
  huart2.Init.WordLength = UART_WORDLENGTH_8B;
  huart2.Init.StopBits = UART_STOPBITS_1;
  huart2.Init.Parity = UART_PARITY_NONE;
  huart2.Init.Mode = UART_MODE_TX_RX;
  huart2.Init.HwFlowCtl = UART_HWCONTROL_NONE;
  huart2.Init.OverSampling = UART_OVERSAMPLING_16;
  if (HAL_UART_Init(&huart2) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN USART2_Init 2 */

  /* USER CODE END USART2_Init 2 */

}

/**
  * @brief GPIO Initialization Function
  * @param None
  * @retval None
  */
static void MX_GPIO_Init(void)
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};
  /* USER CODE BEGIN MX_GPIO_Init_1 */

  /* USER CODE END MX_GPIO_Init_1 */

  /* GPIO Ports Clock Enable */
  __HAL_RCC_GPIOC_CLK_ENABLE();
  __HAL_RCC_GPIOH_CLK_ENABLE();
  __HAL_RCC_GPIOA_CLK_ENABLE();
  __HAL_RCC_GPIOB_CLK_ENABLE();

  /*Configure GPIO pin Output Level */
  HAL_GPIO_WritePin(LD2_GPIO_Port, LD2_Pin, GPIO_PIN_RESET);

  /*Configure GPIO pin : B1_Pin */
  GPIO_InitStruct.Pin = B1_Pin;
  GPIO_InitStruct.Mode = GPIO_MODE_IT_FALLING;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  HAL_GPIO_Init(B1_GPIO_Port, &GPIO_InitStruct);

  /*Configure GPIO pin : LD2_Pin */
  GPIO_InitStruct.Pin = LD2_Pin;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
  HAL_GPIO_Init(LD2_GPIO_Port, &GPIO_InitStruct);

  /* USER CODE BEGIN MX_GPIO_Init_2 */

  /* USER CODE END MX_GPIO_Init_2 */
}

/* USER CODE BEGIN 4 */

/* USER CODE END 4 */

/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{
  /* USER CODE BEGIN Error_Handler_Debug */
  /* User can add his own implementation to report the HAL error return state */
  __disable_irq();
  while (1)
  {
  }
  /* USER CODE END Error_Handler_Debug */
}
#ifdef USE_FULL_ASSERT
/**
  * @brief  Reports the name of the source file and the source line number
  *         where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t *file, uint32_t line)
{
  /* USER CODE BEGIN 6 */
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */
  /* USER CODE END 6 */
}
#endif /* USE_FULL_ASSERT */
