/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : main.c
  * @brief          : Main program body
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2025 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */
/* USER CODE END Header */
/* Includes ------------------------------------------------------------------*/
#include "main.h"
#include "float.h"
/* Private includes ----------------------------------------------------------*/
/* USER CODE BEGIN Includes */
#include "pid.h"
/* USER CODE END Includes */

/* Private typedef -----------------------------------------------------------*/
/* USER CODE BEGIN PTD */

/* USER CODE END PTD */

/* Private define ------------------------------------------------------------*/
/* USER CODE BEGIN PD */
#define LENGTH_MAX 32.0f
/* USER CODE END PD */

/* Private macro -------------------------------------------------------------*/
/* USER CODE BEGIN PM */

/* USER CODE END PM */

/* Private variables ---------------------------------------------------------*/
UART_HandleTypeDef huart2;
static const uint32_t horizontal = 1440; // horizontal position servo-motor

/* USER CODE BEGIN PV */

/* USER CODE END PV */

/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_USART2_UART_Init(void);
/* USER CODE BEGIN PFP */

/* USER CODE END PFP */

/* Private user code ---------------------------------------------------------*/
/* USER CODE BEGIN 0 */

/* USER CODE END 0 */

/**
  * @brief  The application entry point.
  * @retval int
  */
#include <math.h>


void TIM3_PWM_setup() {
	/* GPIO SetUp (PA6 -> TIM3_CH1) */
	RCC->AHB1ENR |= (1 << RCC_AHB1ENR_GPIOAEN_Pos);		// Enable GPIO6
	GPIOA->MODER |= (2 << 12); 							// Alternate function mode
	GPIOA->AFR[0] = (2 << 24); 							// Alternate function n2 for PA6 (TIM3 CH1)
	GPIOA->OSPEEDR 	|= (3 << 12);  						// High Speed for PIN PA6

	/* TIM3 SetUp */
	RCC->APB1ENR |= (1 << RCC_APB1ENR_TIM3EN_Pos); 		// Clock to TIM3

	/* CR1 Configuration */
	TIM3->CR1 &= ~(1 << TIM_CR1_UDIS_Pos); 		// Update event enabled
	TIM3->CR1 &= ~(1 << TIM_CR1_URS_Pos);		// Update event generated by any source
	TIM3->CR1 &= (1 << TIM_CR1_DIR_Pos); 		// Upcounting direction
	TIM3->CR1 &= (0x03 << TIM_CR1_CMS_Pos); 	// (00) Edge aligned mode
	TIM3->CR1 |= (1 << TIM_CR1_ARPE_Pos); 		// Auto reload preload enabled

	TIM3->CCMR1 &= ~(0x03 << TIM_CCMR1_CC1S_Pos); 	// TIM3_CH1 configured as output
	TIM3->CCMR1 |= (1 << TIM_CCMR1_OC1PE_Pos); 		// Preload CCR1 register as well
	TIM3->CCMR1 |= (0x6 << TIM_CCMR1_OC1M_Pos); 	// PWM Mode 1

	TIM3->CCER |= (1 << TIM_CCER_CC1E_Pos); 				// Enable output channel 1
	TIM3->CCER |= (0 << TIM_CCER_CC1P_Pos); 				// Active low

	TIM3->PSC = 84 - 1; 						// CNT incremented every us
	TIM3->ARR = 20000 - 1; 						// Update event every seconds
	TIM3->CCR1 = 1000 - 1;

	TIM3->EGR |= (1 << TIM_EGR_UG_Pos); 		// Fire an update event to update shadow registers
}

volatile uint8_t time_elapsed = 0;
uint16_t counter = 0;
void TIM6_DAC_IRQHandler() {
	if((TIM6->SR >> TIM_SR_UIF_Pos) & 0x01) { //se ha raggiunto il valore di ARR
		NVIC_ClearPendingIRQ(TIM6_DAC_IRQn);
		time_elapsed = 1;                    //ha completato il conteggio
		TIM6->CR1 &= ~(1 << TIM_CR1_CEN_Pos); //disabilita il conteggio
		TIM6->SR &= ~(1 << TIM_SR_UIF_Pos); //  //resetta il flag dell'interrupt
	}
}

/*
 * Misuro il valore di ECHO del sensore
 */
uint8_t measure_collected = 0;
uint32_t measure = 0;
void EXTI1_IRQHandler() {
	NVIC_ClearPendingIRQ(EXTI1_IRQn);
	/*se l'interrupt avviene perchè echo è 1 azzera il contatore e pone un limite alto
	 per evitare overflow abilitando il conteggio e cominciando a contare.*/
	if((GPIOC->IDR >> 1) & 0x01) {
		TIM6->ARR = 65000;
		TIM6->CNT = 0;
		TIM6->CR1 |= (1 << TIM_CR1_CEN_Pos);
		measure_collected = 0;
		/*Se l'interrupt scatta per un fronte di discesa allora il conteggio viene disabilitato, e il
		 * valore a cui siamo arrivati è in measure (tempo di andata e ritorno dell'onda) */
	} else {
		TIM6->CR1 &= ~(1 << TIM_CR1_CEN_Pos);
		measure = TIM6->CNT;
		measure_collected = 1;
	}
	EXTI->PR |= (0x01 << EXTI_PR_PR1_Pos); //va pulito altrimenti risulta ancora la
	                                       //richiesta di interrupt e l'ISR viene richiamata
}


void TIM6_basic_setup() {

	RCC->APB1ENR |= (1 << RCC_APB1ENR_TIM6EN_Pos); 		// Clock to TIM6

	TIM6->CR1 &= ~(1 << TIM_CR1_UDIS_Pos); // Update event enable ( viene chiamato l'handler se c'è overflow e altri
	TIM6->CR1 |= (1 << TIM_CR1_URS_Pos);   // Update event generated only by overflow/underflow
	TIM6->PSC = 84 - 1; 				   // CNT incremented every nanoseconds

	TIM6->DIER |= (1 << TIM_DIER_UIE_Pos); 		// Trigger an interrupt every update event
	NVIC_EnableIRQ(TIM6_DAC_IRQn);				// Enable interrupt for TIM6
	NVIC_SetPriority(TIM6_DAC_IRQn, 0); 		// Set Priority
}

void delay_micro_s(uint16_t delay) {
	TIM6->ARR = delay - 1; //auto-reload value (il timer si resetta a questo valore)
	TIM6->CNT = 0; //valore di conteggio iniziale
	TIM6->CR1 |= (1 << TIM_CR1_CEN_Pos); //abilita il conteggio
	while(!time_elapsed) {}; //finchè time elapsed è 1 ()
	time_elapsed = 0;
}


void hc_sr04_init() {
	RCC->AHB1ENR |= (1 << RCC_AHB1ENR_GPIOCEN_Pos); //abilita il clock alla porta C

	/** Trigger pin configuration **/
	GPIOC->MODER |= (0x01 << 0);  // Set Output PC0 come Trigger (sta alto almeno 10 microsecondi
	                              // appena si abbassa il sensore invia le onde)
	// Push-Pull output
	GPIOC->OTYPER &= ~(0x1 << 0);

	/**Echo pin configuration **/
	GPIOC->MODER  &= ~(0x03 << 2); // Set Input PC1 Echo ci serve leggere per quanto tempo rimane alto

	/* SYStem ConFiGuration (Multiplexer) */
	SYSCFG->EXTICR[0] |= (SYSCFG_EXTICR1_EXTI1_PC); //abilita l'EXTI su PC1 (0010: PC[1]) come sorgente esterna

	/* EXTernal Interrupt configuration */
	EXTI->IMR  |= (EXTI_IMR_IM1); //toglie la maschera all'interrupt
	EXTI->FTSR |= (0x01 << EXTI_FTSR_TR1_Pos);// abilito l'interrupt sul fronte di salita
	EXTI->RTSR |= (0x01 << EXTI_RTSR_TR1_Pos);// abilito l'interrupt sul fronte di discesa

	/* NVIC Configuration */
	NVIC_EnableIRQ(EXTI1_IRQn);
	NVIC_SetPriority(EXTI1_IRQn, 0);

	TIM6_basic_setup();
}

void set_triger() {
	GPIOC->ODR |= (1 << 0); //alza il segnale di trigger
}

void clear_triger() {
	GPIOC->ODR &= ~(1 << 0);//abbassa il segnale di trigger
}

float measure_f_prov;
float beta = 0.3f;
float measure_filtered;
int flag = 1;
float measure_f_prec;
float meas_dist() {
	clear_triger(); 	// keep trigger low
	delay_micro_s(3);	// for at least 3 mu_s

	set_triger();		// set trigger high
	delay_micro_s(10);	// for at least 10 mu_s
	clear_triger();		// clear trigger to start ultrasonic burst transmission

	while(!measure_collected);	// wait for measurement to be collected (look EXTI ISR) finche non
	                            // legge per quanto tempo echo è stato alto
	measure_f_prov = -0.5*0.0343*measure;		// return measurement in cm (twice speed of sound times echo rise time (measure))

	if (flag){
		measure_f_prec = measure_f_prov;
		flag--;
		return measure_f_prov;
	}

	measure_filtered = measure_f_prov * beta + measure_f_prec * (1-beta); // implement Weight. Mov. Avg. Filter

	measure_f_prec = measure_filtered; // for next time

	return measure_filtered;

}

/*
 * ADC configuration
 */

void ADC_init(){
    // Set GPIOA
    RCC->AHB1ENR |= (1 << RCC_AHB1ENR_GPIOAEN_Pos);     // Clock to GPIOA
    GPIOA->MODER |= (3 << GPIO_MODER_MODE0_Pos);        // Set PA0 in Analog mode (correct)

    // ADC configuration
    RCC->APB2ENR |= (1 << RCC_APB2ENR_ADC1EN_Pos);      // enable clock for ADC1

    // Power on ADC first
    ADC1->CR2 |= (1 << ADC_CR2_ADON_Pos);

    // Configure ADC parameters
    ADC1->CR2 |= (1 << ADC_CR2_CONT_Pos);               // Continuous Conversion Mode
    ADC1->CR1 |= (0x03 << ADC_CR1_RES_Pos);            // 12-bit resolution
    ADC1->CR2 &= ~(1 << ADC_CR2_ALIGN_Pos);             // Right alignment

    // Configure sequence: 1 conversion in regular sequence
    ADC1->SQR1 &= ~ADC_SQR1_L_Msk;                      // 1 conversion
    ADC1->SQR3 = 0;                                     // Clear sequence register
    ADC1->SQR3 = 0;                                     // Channel 0 in first position

    // Sample time configuration
    ADC1->SMPR2 &= ~(0x07 << ADC_SMPR2_SMP0_Pos);       // Clear sampling time for channel 0
    ADC1->SMPR2 |= (0x06 << ADC_SMPR2_SMP0_Pos);        // 480 cycles sampling time

    // Interrupt configuration
    ADC1->CR1 |= (1 << ADC_CR1_EOCIE_Pos);              // Enable end-of-conversion interrupt

    // NVIC configuration
    NVIC_EnableIRQ(ADC_IRQn);
    NVIC_SetPriority(ADC_IRQn, 0);

    // Start conversion
    ADC1->CR2 |= (1 << ADC_CR2_SWSTART_Pos);
}

volatile uint16_t reference_pot = 0;
volatile float reference = 0.0f;
void ADC_IRQHandler() {
    if (ADC1->SR & ADC_SR_EOC) {
        reference_pot = (uint16_t) ADC1->DR;
        reference = (float)reference_pot * (-LENGTH_MAX/pow(2,6));
        ADC1->SR &= ~ADC_SR_EOC;  // Clear the interrupt flag
    }
}



float measure_f;
float uk;
float pwm;
int main(void)
{
  /* MCU Configuration--------------------------------------------------------*/

  /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
  HAL_Init();

  /* Configure the system clock */
  SystemClock_Config();

  /* Initialize all configured peripherals */
  MX_GPIO_Init();
  MX_USART2_UART_Init();

  //setup servo motor
  TIM3_PWM_setup();

  //setup ultrasound sensor
  hc_sr04_init();

  // ADC
  ADC_init();

  /* PID tuning and initialization START */

  float tc = 0.09; // 70ms
  float kp = 3.15f;    // moderate proportional
  float ti = 8.0f;    // 1s integral time → removes steady-state error in a few seconds
  float td = 0.001f;    // 1ms derivative time → gentle slope damping
  float N  = 10.0f;   // filter pole → rolls off derivative above ~1/(Td/N)=100kHz
  float tw = ti;      // back-calc time constant ≃ Ti (you can also try Ti/10)
  float u_min = -65.0f;  // PWM min 720 -> 2160
  float u_max = 65.0f;  // PWM max (assuming you scale from -65° to 65° which is servo angle )

  Pid_s *pid = pid_create(tc, kp, ti, td, N, u_min, u_max, tw);

  /* PID tuning and initialization END */

  TIM3->CR1 |= (1 << TIM_CR1_CEN_Pos);

  /*
   * Set bar angle at 0°
   */

  TIM3->CCR1 = horizontal -1;

  while (1)
  {
    /* USER CODE END WHILE */
	  measure_f = meas_dist();	// take measurement
	  if (fabs(measure_f-reference)>=0.01){
		  uk = pid_calculate(pid, measure_f, reference);
		  pwm = ((uk + 90) / 180) * 1440 + 720;
		  TIM3->CCR1 = (uint32_t) pwm;
	  }
	  HAL_Delay(10);

  }
}

/**
  * @brief System Clock Configuration
  * @retval None
  */
void SystemClock_Config(void){
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  /** Configure the main internal regulator output voltage
  */
  __HAL_RCC_PWR_CLK_ENABLE();
  __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE3);

  /** Initializes the RCC Oscillators according to the specified parameters
  * in the RCC_OscInitTypeDef structure.
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
  RCC_OscInitStruct.HSIState = RCC_HSI_ON;
  RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSI;
  RCC_OscInitStruct.PLL.PLLM = 16;
  RCC_OscInitStruct.PLL.PLLN = 336;
  RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV4;
  RCC_OscInitStruct.PLL.PLLQ = 2;
  RCC_OscInitStruct.PLL.PLLR = 2;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }

  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_2) != HAL_OK)
  {
    Error_Handler();
  }
}

/**
  * @brief USART2 Initialization Function
  * @param None
  * @retval None
  */
static void MX_USART2_UART_Init(void){
  huart2.Instance = USART2;
  huart2.Init.BaudRate = 115200;
  huart2.Init.WordLength = UART_WORDLENGTH_8B;
  huart2.Init.StopBits = UART_STOPBITS_1;
  huart2.Init.Parity = UART_PARITY_NONE;
  huart2.Init.Mode = UART_MODE_TX_RX;
  huart2.Init.HwFlowCtl = UART_HWCONTROL_NONE;
  huart2.Init.OverSampling = UART_OVERSAMPLING_16;
  if (HAL_UART_Init(&huart2) != HAL_OK)
  {
    Error_Handler();
  }
}

/**
  * @brief GPIO Initialization Function
  * @param None
  * @retval None
  */
static void MX_GPIO_Init(void)
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};
  /* USER CODE BEGIN MX_GPIO_Init_1 */

  /* USER CODE END MX_GPIO_Init_1 */

  /* GPIO Ports Clock Enable */
  __HAL_RCC_GPIOC_CLK_ENABLE();
  __HAL_RCC_GPIOH_CLK_ENABLE();
  __HAL_RCC_GPIOA_CLK_ENABLE();
  __HAL_RCC_GPIOB_CLK_ENABLE();

  /*Configure GPIO pin Output Level */
  HAL_GPIO_WritePin(LD2_GPIO_Port, LD2_Pin, GPIO_PIN_RESET);

  /*Configure GPIO pin : B1_Pin */
  GPIO_InitStruct.Pin = B1_Pin;
  GPIO_InitStruct.Mode = GPIO_MODE_IT_FALLING;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  HAL_GPIO_Init(B1_GPIO_Port, &GPIO_InitStruct);

  /*Configure GPIO pin : LD2_Pin */
  GPIO_InitStruct.Pin = LD2_Pin;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
  HAL_GPIO_Init(LD2_GPIO_Port, &GPIO_InitStruct);


}



/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{
  /* USER CODE BEGIN Error_Handler_Debug */
  /* User can add his own implementation to report the HAL error return state */
  __disable_irq();
  while (1)
  {
  }
  /* USER CODE END Error_Handler_Debug */
}
#ifdef USE_FULL_ASSERT
/**
  * @brief  Reports the name of the source file and the source line number
  *         where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t *file, uint32_t line)
{
  /* USER CODE BEGIN 6 */
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */
  /* USER CODE END 6 */
}
#endif /* USE_FULL_ASSERT */
